import './common/common.scss'
import './components/header/header'
import './components/breadcrumbs/breadcrumbs'
import './components/footer/footer'
import './components/menu/menu'
import './components/catalog/catalog'
import './components/product/product'
