import './common/common.scss'
import './components/header/header'
import './components/footer/footer'
import './components/menu/menu'
import './components/banner/banner'
import './components/contact-form/contact-form'
